eureka:
  url: 192.168.33.12
  port: 8081
user-service:
  id: user-service
  path: /myusers/**
api-gateway:
  ip: 192.168.33.12
trial-service:
  ip: 192.168.33.12
PROXY_HOST: web-proxy.sgp.hp.com
PROXY_PORT: 8080
PROXY_SCHEME: http